---
version: "3.7"
services:

  gateway:
    image: devopsfaith/krakend:1.2
    container_name: gateway
    ports:
    - 8080:8080
    volumes:
    - ./krakend.yaml:/etc/krakend/krakend.yaml
    entrypoint: [ "/usr/bin/krakend" ]
    command: [ "run", "--debug", "--config", "/etc/krakend/krakend.yaml", "--port", "8080" ]
  
  identity-service:
    build:
      context: ./identity-service
    ports:
    - 9005
    environment:
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=9005
    - LOGGER_LEVEL=debug 
    - SERVER_READ_TIMEOUT=5000
    - SERVER_IDLE_TIMEOUT=15000
    - JWT_VALIDATION_ENABLED=true # disable if krakend handles auth!
    - JWT_PATHS_WHITELIST=/auth/register,/auth/login,/jwks.json
    - JWT_SECRET=secret
    - JWT_EXP_SECS=86400
    - JWT_ALGO=HS256

  cart-service:
    build:
      context: ./cart-service
    ports:
    - 9002
    environment:
    - APP_ENV=dev
    - SERVER_HOST=0.0.0.0
    - SERVER_PORT=9002
    - LOCAL_STORE_ENABLED=true
    - LOGGER_LEVEL=debug
    - SERVER_READ_TIMEOUT=5s
    - SERVER_WRTIE_TIMEOUT=10s
    - SERVER_IDLE_TIMEOUT=15s
