apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 2
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:1.2
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json"]
        env:
        - name: KRAKEND_PORT
          value: "8000"
        volumeMounts:
          - name: config
            mountPath: /etc/krakend/
      volumes:
        - name: config
          configMap:
            name: krakend-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: krakend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-configmap
data:
  krakend.json: |
    {
      "version": 2,
      "port": 8000,
      "endpoints": [
        {
          "endpoint": "/auth/login",
          "method": "POST",
          "output_encoding": "json",
          "extra_config": {
            "github.com/devopsfaith/krakend-ratelimit/juju/router": {
              "maxRate": 10,
              "clientMaxRate": 5,
              "strategy": "ip"
            }
          },
          "backend": [
            {
              "url_pattern": "/auth/login",
              "encoding": "json",
              "sd": "static",
              "method": "POST",
              "host": [
                "http://identity-service:9005"
              ]
            }
          ]
        },
        {
          "endpoint": "/auth/register",
          "method": "POST",
          "output_encoding": "no-op",
          "backend": [
            {
              "url_pattern": "/auth/register",
              "encoding": "no-op",
              "sd": "static",
              "method": "POST",
              "extra_config": {},
              "host": [
                "http://identity-service:9005"
              ]
            }
          ]
        },
        {
          "endpoint": "/cart",
          "method": "GET",
          "output_encoding": "json",
          "extra_config": {
            "github.com/devopsfaith/krakend-jose/validator": {
                "alg": "HS256",
                "jwk-url": "http://identity-service:9005/jwks.json",
                "disable_jwk_security": true,
                "kid": "userid"
            }
          },
          "backend": [
            {
              "url_pattern": "/{JWT.userid}/cart",
              "encoding": "string",
              "sd": "static",
              "method": "GET",
              "extra_config": {},
              "host": [
                "http://cart-service:9002"
              ],
              "disable_host_sanitize": true,
              "is_collection": false
            }
          ]
        }
      ]
    } 
