---
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: cart-service
    context: ./cart-service
  - image: identity-service
    context: ./identity-service

deploy:
  helm:
    releases:
    - name: gateway
      chartPath: ./kubernetes-helmcharts/gateway
      valuesFiles:
      - ./kubernetes-helmcharts/gateway/values.yaml
      version: 0.1.0
    - name: cart-service
      chartPath: ./kubernetes-helmcharts/cart-service
      valuesFiles:
      - ./kubernetes-helmcharts/cart-service/values.yaml
      artifactOverrides:
        image.repository: cart-service
      version: 0.1.0
    - name: identity-service
      chartPath: ./kubernetes-helmcharts/identity-service
      valuesFiles:
      - ./kubernetes-helmcharts/identity-service/values.yaml
      artifactOverrides:
        image.repository: identity-service
      version: 0.1.0
